# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default template is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# timezone =

# max length of characters to slugify the migration summary
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported
# relative to the path specified in script_location
# prepend_sys_path = false

# version path separator; default is os.pathsep.
# Use a space to allow multi-line version_locations
# version_path_separator = ' '

# set to 'true' to search source files recursively for
# revision scripts; only relevant if version_locations includes multiple paths
# recursive_version_locations = false

# the output encoding used when writing new migration files
# output_encoding = utf-8

sqlalchemy.url = postgresql://credittech:credittech_dev@localhost:5432/credittech


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.

# format using "ruff" if present
# hooks = ruff
# ruff.type = console_scripts
# ruff.entrypoint = ruff
# ruff.options = format REVISION_SCRIPT_FILE

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
